name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook setup_vm.yml -i inventory_file # Replace with your inventory file path

      - name: Install InSpec
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash
          sudo chef gem install inspec

      - name: Run InSpec Compliance Tests
        run: inspec exec compliance_profile # Replace with your InSpec profile path
