---
- name: Configure Development VM
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - nginx
          - git
          - python3
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure default nginx webpage
      copy:
        dest: /var/www/html/index.html
        content: "Welcome to the DevOps Challenge"

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Set SSH port to 22
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 22'

    - name: Create devops user
      user:
        name: devops
        shell: /bin/bash
        groups: sudo
        state: present
        create_home: yes
    
    - name: Ensure .ssh directory exists for devops user
      ansible.builtin.file:
        path: /home/devops/.ssh
        state: directory
        owner: devops
        group: devops
        mode: '0700'

    - name: Generate SSH key pair for devops user
      ansible.builtin.openssh_keypair:
        path: /home/devops/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present
      register: ssh_key

    - name: Copy public key to authorized_keys
      ansible.builtin.copy:
        src: "{{ ssh_key.public_key }}"
        dest: /home/devops/.ssh/authorized_keys
        owner: devops
        group: devops
        mode: '0600'

    - name: Ensure correct permissions for authorized_keys
      ansible.builtin.file:
        path: /home/devops/.ssh/authorized_keys
        owner: devops
        group: devops
        mode: '0600'
    
    # - name: Generate SSH key
    #   command:
    #     cmd: ssh-keygen -t rsa -b 2048 -f /home/devops/.ssh/id_rsa -N ""
    #   args:
    #     creates: /home/devops/.ssh/id_rsa

    # - name: Copy public key to authorized_keys
    #   copy:
    #     src: /home/devops/.ssh/id_rsa.pub
    #     dest: /home/devops/.ssh/authorized_keys
    #     owner: devops
    #     group: devops
    #     mode: '0600'

    # - name: Ensure .ssh directory has correct permissions
    #   file:
    #     path: /home/devops/.ssh
    #     owner: devops
    #     group: devops
    #     mode: '0700'

