name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read

jobs:
  terraform:
    name: 'Setup VM'
    runs-on: ubuntu-24.04
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt-get install -y ansible

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.9.0"
    
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # # Checks that all Terraform configuration files adhere to a canonical format
    - name: Format Terraform
      run: terraform fmt -recursive
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terrafo rm
    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan -input=false

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: |
        terraform apply plan.tfplan

    # - name: Gather Env
    #   run: |
    #     echo "INSTANCE_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
    #     echo "PRIVATE_KEY=$(terraform output -raw private_key)" >> $GITHUB_ENV


    - name: install chef
      uses: actionshub/chef-install@main
      with:
        channel: current
        project: inspec

    - name: Run InSpec Profile
      run: |
        terraform output -raw private_key > /tmp/private.pem
        cat /tmp/private.pem
        HOST=$(terraform output -raw instance_public_ip)
        export CHEF_LICENSE="accept"
        export INSPEC_LICENSE_KEY="free-178aea45-29fb-4bf4-a436-432256575727-6119"
        inspec exec ./vm_configuration_checks.rb --target ssh://ubuntu@$HOST -i /tmp/private.pem --sudo


